### ISSUE TITLE
ICE error 1007 and Websockit error 1002 

### ISSUE THREAD

**Issue by ibrahim-quraishi** [bigbluebutton/bbb-install#304]
Hi, All I am new to BBB, I had successfully install BBB using the Ubuntu 16.04 script got it to work a couple of time. However, when I do a new install now I am getting ICE 1007 error. 
I have used the following command wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -s dev02.theagileops.com -e ibrahim@agileops.co.uk -w -g

And when I test it I got the error ICE 1007.

I followed the steps to change the Freeswitch IP to public, To be exact, I have followed everything from https://docs.bigbluebutton.org/2.2/configure-firewall.html
And after that, I am getting websockit error  1002 error. 
I have updated the Kurento with the following IP 173.194.71.127:19302
and edit the freeswitch files which is shown on the configure firewall page.

I have copied the output from bbb-conf --check command so you can see the changes I have done. 
I have installed this 8 times in 2 days and still not able to get it to work, I will appreciate if anyone can point me in the right direction. 

All the ports are open on Azure. 
Following ports are open on Azure Instance. 

22 TCP | Any | Any | Allow |  
443 | TCP | Any | Any | Allow |  
80 | TCP | Any | Any | Allow |  
16384-32768 | UDP | Any | Any | Allow |  
5060-5070 | UDP | Any | Any | Allow |  
7443 | TCP | Any | Any | Allow |  
1935 TCP | Any | Any | Allow |  

Any help will be greatly appreciated.

root@dev02:/home/azureuser# bbb-conf --check

BigBlueButton Server 2.2.29 (2244)
Kernel version: 4.15.0-1098-azure
Distribution: Ubuntu 16.04.7 LTS (64-bit)
Memory: 16426 MB
CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
bigbluebutton.web.serverURL: https://dev02.theagileops.com
defaultGuestPolicy: ALWAYS_ACCEPT
svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
server name: dev02.theagileops.com
port: 80, [::]:80
port: 443 ssl
bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
Port test (tunnel): rtmp://dev02.theagileops.com
red5: dev02.theagileops.com
useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
local_ip_v4: 10.0.6.6
external_rtp_ip: 20.75.72.65
external_sip_ip: 20.75.72.65

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
ext-rtp-ip: 20.75.72.65
ext-sip-ip: 20.75.72.65
ws-binding: :5066
wss-binding: 10.0.6.6:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
playback_host: dev02.theagileops.com
playback_protocol: https
ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
proxy_pass: 20.75.72.65

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
kurento.ip: 10.0.6.6
kurento.url: ws://127.0.0.1:8888/kurento
kurento.sip_ip: 10.0.6.6
localIpAddress: 10.0.6.6
recordScreenSharing: true
recordWebcams: true
codec_video_main: VP8
codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
build: 1081
kurentoUrl: wss://dev02.theagileops.com/bbb-webrtc-sfu
enableListenOnly: true

Potential problems described below
IP does not match:
IP from ifconfig: 10.0.6.6
/etc/nginx/sites-available/bigbluebutton: dev02.theagileops.com

Error: Unable to connect to port 1935 (RTMP) on dev02.theagileops.com

Warning: The setting of 20.75.72.65 for proxy_pass in

/etc/bigbluebutton/nginx/sip.nginx
does not match the local IP address (10.0.6.6).
(This is OK if you've manually changed the values)

docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed

I have not deleted this installation to work with any developer who can help me I will be available to run and test or make any changes to this setup to get this to work.
Thanks in advance.

**Comment by EmmyGraugans** [comment]
I just had the same (or at least very similar) issue, albeit when trying to install bbb2.3 – apparently the script bbb-conf checks for the IP-address in most cases via `IP=$(hostname -I | cut -f1 -d' ')` – unfortunately, the output of `hostname -I` is for me:
```
# hostname -I
10.21.22.45 <real.ip> 172.21.0.1 172.17.0.1 172.18.0.1 
```

That leads to the installation script entering the (wrong and not reachable from the outside) address 10.21.22.45 instead of the <real.ip>...

The other part, that looks for ifconfig with some convoluted grep, cut and awk (which is currently only called if a network named "venet0:0" is present) works only in Ubuntu 16.04, but not in 18.04 which has a different output of `ifconfig`...

Current line (correct for Ubuntu 16.04):
```
IP=$(ifconfig | grep -v '127.0.0.1' | grep -E "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | tail -1 | cut -d: -f2 | awk '{ print $1}')
```

Variant that works in Ubuntu 16.04 *and* Ubuntu 18.04:
```
IP=$(ifconfig | grep -v '127.0.0.1' | grep -E "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | tail -1 | awk '{ print $2}' | cut -d: -f2)
```

The main problem seems to be that both `hostname -I` *and* `ifconfig` don't have a determined order of IP-Addresses, so I guess the only option would be to read all addresses, iterate over them and analyse the result for private network, in order to use the (first?) external network, if it finds any... I might have a go at that later, for now the `ifconfig` line above is enough for me, because in this one server that I am interested in currently, it works (it doesn't in at least one other, because the ifconfig returns the 10.x address there).

**Comment by ffdixon** [comment]
Updated the logic for determining the host IP address here https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L443
