### ISSUE TITLE
Install coturn on Ubuntu 20.04 (focal)

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/bbb-install#333]
The [documentation](https://docs.bigbluebutton.org/2.2/setup-turn-server.html#required-software) recommends that coturn should be installed on Ubuntu 20.04 (focal). `bbb-install` currently only support installing coturn on 18.04 (bionic).

`bbb-install` should support and recommend installing coturn on Ubuntu 20.04 to be consistent with the documentation.

**Comment by ffdixon** [comment]
Fixed with https://github.com/bigbluebutton/bbb-install/commit/1b19b024ebbe9261d8280011475e88562d4610bb.

**Comment by relecand** [comment]
Hi Fred,

just few questions and hints:

1. https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L1163

```
ExecStart=
ExecStart=/usr/bin/turnserver --daemon -c /etc/turnserver.conf --pidfile /run/turnserver/turnserver.pid --no-stdout-log --simple-log --log-file /var/log/turnserver/turnserver.log
```

First line is empty.

2. https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L1159

```
  cat > /etc/systemd/system/coturn.service.d/ansible.conf <<HERE
```

May be coturn.conf would be better?


3. Would it be possible to integrate /etc/systemd/system/coturn.service.d/ansible.conf into /usr/lib/systemd/system/coturn.service?

Like described here: https://docs.bigbluebutton.org/2.2/setup-turn-server.html#configure-coturn

with ```sudo systemctl edit --full coturn```

All the best,

Christian

**Comment by ffdixon** [comment]
Thanks for the feedback!

(1) I think this is necessary to override existing settings ([example](https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services)).

(2) Good catch, [renamed](https://github.com/bigbluebutton/bbb-install/commit/0c5192ea420c58380dcc37916761eecff456a758) this to `override.conf` 

(3) I think its best to do this as an override so that any updates to `coturn` package won't overwrite these extensions.

**Comment by relecand** [comment]
Great, thank you!

**Comment by relecand** [comment]
Hi Fred, 

just two hints more:

**1. In the docs there is a wrong UDP port range:**

49152-65535 | UDP | relay ports range

https://github.com/bigbluebutton/bbb-install#install-a-turn-server

**2. min port**

https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L1112

should it be:

`min-port=32768`

instead of

`min-port=32769`

?

see: https://docs.bigbluebutton.org/2.2/setup-turn-server.html#required-ports

The min-port there is also: 32769

https://docs.bigbluebutton.org/2.2/setup-turn-server.html#configure-coturn

All the best,

Christian

**Comment by hex-m** [comment]
@relecand thanks! But commenting on a closed issue may not get your valuable information the attention it deserves.

As FreeSWITCH uses UDP-ports up to `32768` I think coturn should use `min-port=32769` as it might be possible to install it on the same server in the future. The idea was to double the number of available ports from 16383 to 32766 - so the range should start at 32769.

That would mean the [documentation](https://github.com/bigbluebutton/bigbluebutton.github.io/blob/master/_posts/2019-02-14-setup-turn-server.md#required-ports) should be updated but the `bbb-install` script is correct the way it is.

The `bbb-install` [readme](https://github.com/bigbluebutton/bbb-install/blob/master/README.md#install-a-turn-server) needs an update to the port-range too.

Feel free create new issues (or even better PRs) for those changes.
