### ISSUE TITLE
Server on a network without internet access

### ISSUE THREAD

**Issue by MOPO3KO** [bigbluebutton/bbb-install#372]
Hey!
I am trying to start a server that will work without internet access.
Tried different installations via bbb-install.sh script.
For example "wget ​​-qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s - -a -d -v bionic-23" does the installation, but I can't start the server even by creating a homemade one certificate.
Since the server is bad without Internet access, there is no usual domain name for it.
I tried to set my internal domain name and register it in the local DNS, and then set this name to "bbb-conf --setip localDNS".
But this also does not work, when connecting via https and starting the room, I always get the error "java.lang.NullPointerException"
I tried to double-check the configuration files according to the instructions of version 2.2, but this did not help either.

I ask for help to start the server to work with a local domain and without access to the Internet.

**Comment by joo4mart** [comment]
For the installation you always need internet connection for download of all the packages (ubuntu packages, external packages). But after the complete installation there should be a way running BBB offlline. Just try it.

**Comment by michi-80337** [comment]
The install.sh scripts -p switch should help to get BBB and its dependencies installed when you are sitting behind a firewall. If installation succeeded without error, it would be very interesting to know more about the circumstances. It's hard to debug an "it doesn't work" issue without that. If there was an error message from the installation script, You have a hint where the problem lies. You could then take a closer look into documentation and the diverse mailing lists. ...

**Comment by GhaziTriki** [comment]
You always need internet to install BigBlueButton or create an image. After that it can perfectly be used without any internet connection with a LAN.
