### ISSUE TITLE
Script fails due to missing `wget`

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/bbb-install#387]
Without GNU Wget installed, the script fails with:

    bbb-install: Unable to locate packages for bionic-23-s at ubuntu.bigbluebutton.org.

As the stdout/stderr is redirected to `/dev/null`, the cause is not clear.

https://github.com/bigbluebutton/bbb-install/blob/1c71e49b0f4f3061e5d3fa524c0b68e33e93d2ba/bbb-install.sh#L546-L548

It’d be great if the script ensured, *wget* is installed.

**Comment by EmmyGraugans** [comment]
Well, the instructions on how to use `bbb-install.sh` suggest to execute
```
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -a -v bionic-23 -s bbb.example.com -e info@example.com
```

So if one follows that, it would be rather obvious that wget needs to be installed, but yes, the script itself should probably check as well, that programs that it uses are actually present.

**Comment by paulmenzel** [comment]
I thought about that too, but the exact wording is:

> As an example, the following command installs BigBlueButton 2.3 using hostname bbb.example.com and email address (for Let’s Encrypt) notice@example.com.

And a lot of people are easily able to use curl instead of GNU Wget, so it’d be great if the script checked for and, if necessary, installed the package *wget*.

**Comment by EmmyGraugans** [comment]
@ffdixon: Just commenting on one line in the commit https://github.com/bigbluebutton/bbb-install/commit/cc94598a94d1a0ef1e8c0dd869abbda8fface592#diff-b02a2e8accf3dc268b4cc8c4a6ce2b6b51cbaee1a254fb674c6429fbfdf5ef81R228 : 

Technically, the line `sudo add-apt-repository universe` needs a preceding line `need_pkg software-properties-common` since the command add-apt-repository is not available in a minimal Ubuntu-Installation such as for example lxc provides.
