### ISSUE TITLE
installation for ubuntu 20.04

### ISSUE THREAD

**Issue by smb-sh** [bigbluebutton/bbb-install#389]
Hi,
Please provide the installation version for Ubuntu 20.04 as well

**Comment by ffdixon** [comment]
HI @smb-sh, we're currently pegged on 18.04 with Kurento.  We're looking at other options for media servers that can let us move to 20.04.  There is active work on this area.

**Comment by uneek9** [comment]
Hi @ffdixon, 
The reason I was looking to also update from 18.04 to 20.04 is because of this issue https://groups.google.com/g/bigbluebutton-setup/c/_039NCnoYkI I am also having.  However, I assume there are others with 18.04 that are not getting ICE 1007 and can leave the Turn server running without having to reboot every time about an hour before sessions begin.  Is there a fix? 

My other question is if I do a fresh new install 20.04 with a new letsencrypt cert on a new server and it doesn't work out, can I just go back to using my initial old server 18.04 or will my old letsencrypt not work anymore as it's domain specific (since I would have ran a new cert for the new 20.04 box)?

Thank you very much

**Comment by ffdixon** [comment]
We recommend you run your TURN server on Ubuntu 20.04 and your BigBlueButton server on 18.04.
