### ISSUE TITLE
Fresh install on a virtual machine fails with "Did not detect nodejs 16.x candidate for installation"

### ISSUE THREAD

**Issue by olma67** [bigbluebutton/bbb-install#614]
Hi, guys!
I followed the prerequisits of https://docs.bigbluebutton.org/2.5/install.html, fired the installscript and ran in to the following error:

`bbb-install: Did not detect nodejs 16.x candidate for installation`

Indeed I had v10, which comes with Ubuntu 20.04. I removed v10 and tried to install v16.x through PPA which doesnt held a release file (anymore). I succeeded with nvm and installed v16.19.1.  Check: 
```
root@bbb:~# node -v
v16.19.1
```
I ran the installscript again but get stuck at the same point. I rebooted the server, and tried v18.x .... nothing.
It seems that the installscript doesn't recognize nodejs at all.

Any suggestions how I can install bbb ?

Thanks.

**Comment by ffdixon** [comment]
Can you try installing BigBlueButton 2.6-rc.5 and let us know if you still encounter this issue.

  https://docs.bigbluebutton.org/2.6/install.html

**Comment by olma67** [comment]
Hi, Fred!
Thanks for your help.

Using the 2.6 installscript doesn't change anything. Same error with nodejs v16 is installed:

```
## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://ppa.launchpad.net/bigbluebutton/support/ubuntu focal InRelease      
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease                    
Hit:4 http://archive.ubuntu.com/ubuntu focal-security InRelease                  
Get:5 https://ubuntu.bigbluebutton.org/focal-260 bigbluebutton-focal InRelease [2,532 B]
Err:5 https://ubuntu.bigbluebutton.org/focal-260 bigbluebutton-focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 37B5DD5EFAB46452
Reading package lists... Done
W: GPG error: https://ubuntu.bigbluebutton.org/focal-260 bigbluebutton-focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 37B5DD5EFAB46452
E: The repository 'https://ubuntu.bigbluebutton.org/focal-260 bigbluebutton-focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting
bbb-install: Did not detect nodejs 16.x candidate for installation
root@bbb:~# 
```


Sorry.

**Comment by ffdixon** [comment]
Thanks for sharing @olma67 -- this will definitely help others.

**Comment by boarsteas1** [comment]
This solution here did not solve the problem for me, or I got something wrong.
Anyway, I installed the correct Nodejs 16 manually, commenting out the nodejs check, but had issues with webrtc-sfu and etherpad. Then I went back and tried to fix the installation error, finding this:
https://github.com/nodesource/distributions/issues/1266#issuecomment-931600179
Everything works as expected for now.
I used a fresh installed ubuntu 20.04, updated and restarted.  I am not experienced enough to propose what's the right way to go here, or if i am the only one with this issue for some reason, but i post it here as another quick and dirty workaround. Keep up the good work, otherwise the installer works flawless 👍
