### ISSUE TITLE
Script hangs when package maintainer prompts for input.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bbb-install#7]
Twice,  on two different hosting providers (digital ocean)  the script will prompt to decide whether to keep or overwrite a conf like grub etc...     Cant continue, no response on key board.  I open another shell and can see no disk usage increasing, so installation is stalled.

i kill the apt-get processes,  run dpkg configure -a and then run apt-get dist-upgrade. apt-get update

After that the bbb-install.sh is ran again to finish successfully.

**Comment by ffdixon** [comment]
We're seeing this as well. We suspect it's because the input is being read from the pipe, not the keyboard.

There are two workarounds. The first would be to do a `sudo apt-get update && sudo apt-get dist-upgrade` before running the script. 

Alternatively, you could download the script first, then then it at the command line, should also work

~~~
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh
chmod +x bbb-install.sh
./bbb-install.sh -v xenial-200
~~~
It should be possible to prefill the choices for grub update using debconf-set-selections, as in

~~~
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
~~~

We just need to figure out the appropriate settings.  If anyone has suggestions, please feel free to add them to this ticket.

**Comment by ffdixon** [comment]
This line does the trick: https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L150
