### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Alimotreb** [bigbluebutton/bbb-install#71]
hi all 
i want use bigbluebuttun 
my OS ubunto 16

step 1: wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta
step 2: wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta -s onlineconf.digialpha.net -e info@digialpha.net
step 3 : wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta -s onlineconf.digialpha.net -e info@digialpha.net -g

step 4: reboot 

after the run command i get an error : 
https://onlineconf.digialpha.net/b

but this link : https://onlineconf.digialpha.net/demo/demo1.jsp  is up!

can you  help me?
where is the problem from?
thansk

**Comment by haviduck** [comment]
Facing the same issue. Narrowed it down to greenlightv2 and sqlite3. Its not able to create settings table and the composer up fails.

**Comment by ffdixon** [comment]
Got it -- we'll take a closer look.

**Comment by haviduck** [comment]
Hey fred :) Tried all night. Ended up with the conclusion that greenlight tries a select on rooms.deleted and users.deleted. Since those columns arent in the original schema it fails. Trying to alter the tables throws an error that it now already exists. I dont write ruby so im not more help than that.

**Comment by haviduck** [comment]
Ok so its working now.
The issue remains but my steps were:
1 Composer up
2 Exec into the db container, run psql alter tables
3 composer down and up
4 alter tables and drop the deleted columns from rooms and users
5 recreate the container (i used portainer).


And just in time for work! Phew!

**Comment by Alimotreb** [comment]
Hello friends
I could say I rebuilt the server about 10 times and got it installed first
But it still gives the same error
But after installing, I encounter this error that I also posted a link to see
Tell me if you have a command, something, or the installation process if I'm wrong

thanks

**Comment by haviduck** [comment]
@Alimotreb  its due to tables not-existing and then existing.  my guide above is severely lacking and i know fred will come up with a solution, but if u exec into the containers, create the tables, composer up the containers, delete the tables then recreate that entire container you are golden.  its not pretty and itll break on an update, but if u just need it asap itll work that way. lets wait for team BBB to come with a real fix before settling for my hackish solution :)  if not, drop me a pm and ill be happy to assist.

**Comment by Alimotreb** [comment]
hi
@haviduck 
Thank you dear friend
I am also waiting for the update to fix the issue
but
Can you give us more guidance on what should be done?

**Comment by haviduck** [comment]
ok, my dirty hack to get this going is as follows (given that u are using postgres and have portainer up and running): 
```
cd ~/greenlight
exec -it greenlight_db_1 /bin/bash
psql -d greenlight_production
ALTER TABLE rooms ADD COLUMN deleted boolean;
ALTER TABLE users ADD COLUMN deleted boolean;
\q 
exit
docker-compose down && docker-compose up -d && docker-logs greenlight_db_1 --follow
( at this point u should see an error saying that the table column allready exists).
exec -it greenlight_db_1 /bin/bash
psql -d greenlight_production 
ALTER TABLE rooms DROP COLUMN deleted;
ALTER TABLE users DROP COLUMN deleted;
\q
exit
```
Now go to portainer, select the greenlight-v2 container and choose recreate - theres probably a docker command that does the exact same. when thats done /b should be accessible and working. if not tail the logs and see what it says. mind you that the .env and docker-compose.yml conf's are pretty important regardless of my hack.

**Comment by GhaziTriki** [comment]
Please seek help in the forums [groups.google.com/g/bigbluebutton-greenlight](https://groups.google.com/g/bigbluebutton-greenlight)
