### ISSUE TITLE
Test install on Azure

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bbb-install#80]
We have logic to detect the public/private IP address when installing on EC2 and GCE -- need to add similar detection for Azure.

**Comment by GhaziTriki** [comment]
It might be good to add a new install parameter `-p` for platfrom.
A sample use would be `-p aws` for AWS, `-p do` for DigitalOcean or `-p gce` for Google Compute Engine and so on.

As example detecting the IP address on digital ocean relies on its API,
`http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address` for the public IP address and `http://169.254.169.254/metadata/v1/floating_ip/ipv4/ip_address` if a floating IP address is assigned.

**Comment by GhaziTriki** [comment]
By the way `bbb-conf` has to follow and it needs to detect the platform.

**Comment by trs80** [comment]
This works for Azure:
`curl -s -H Metadata:true "http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/0/publicIpAddress?api-version=2019-08-15&format=text"`

For detection, perhaps the existence of `/etc/waagent.conf` ? Wait the script already checks the dhcp options https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L399 but the install fails further down because it says the DNS lookup doesn't match the local IP. Oh, it failed https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L424 because I didn't have the external firewall configured to allow port 80 and 443 in before running the script.
