### ISSUE TITLE
ffmpeg download failed

### ISSUE THREAD

**Issue by ncresswell** [bigbluebutton/bbb-install#87]
When trying to install BBB via the install script, it fails as it cannot find the install files for FFMPEG. 

![image](https://user-images.githubusercontent.com/23178133/70578241-02c9f380-1c12-11ea-9ca1-0255b553ec21.png)

It seems the provider of those files has moved them.
![image](https://user-images.githubusercontent.com/23178133/70578308-2db44780-1c12-11ea-8e1a-540015dc53bd.png)

![image](https://user-images.githubusercontent.com/23178133/70578744-7fa99d00-1c13-11ea-8417-b4e004d87c52.png)

![image](https://user-images.githubusercontent.com/23178133/70578293-212fef00-1c12-11ea-847b-22b5d939863d.png)

Is there another way to install using an alternate repo ?

**Comment by ffdixon** [comment]
I am personally very sympathetic to the maintainer of the repository.  Open source developers need to earn money too, and because you do your work under an open source license doesn't mean you work for nothing.

Hopefully some of the companies that have been benefiting from this repository start sponsoring the project, especially the backport of `ffmpeg`. 

Until then, we'll also start looking for other alternatives.   We'll also see if we can revert back to the (old) built-in version of `ffmpeg` in 16.04 for a while until we move to 18.04 (which has a much newer version of `ffmpeg`).

**Comment by ncresswell** [comment]
in the meantime, i rolled back to BBB 1.0

**Comment by pr0totyp** [comment]
When will there be a version of bbb for 18.04 or 20.04? 
I am trying to setup bbb since some days and this is very frustrating.

Maybe remove ffmpeg from your apt dependencies and we can install ffmpeg 4 via snap.

**Comment by ffdixon** [comment]
We plan to move to 18.04 as part of the next release (2.3).  

I can understand your frustration, and it's probably mirrored with by the maintainer of the `ffmpeg` repository who sees his work used by companies commercial without any compensation.

We're looking a compiling our own version of `ffmpeg` for BigBlueButton.  We'll update this thread when we have more updates.

**Comment by pr0totyp** [comment]
Great thanks a lot for your effort! Looking forward to use your great project :)

When will the BBB 2.3 be released?

**Comment by ffdixon** [comment]
We release on quality, not dates :-).

  http://docs.bigbluebutton.org/support/faq.html#development-priorities
